apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-app
  template:
    metadata:
      labels:
        app: taskmanager-app
    spec:
      containers:
      - name: taskmanager-app
        image: rhylton4/taskmanager-app:tag
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-app
spec:
  selector:
    app: taskmanager-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
